# Naïve Bayesian Classifier for Document Classification
This notebook applies the Naïve Bayes model to classify messages as spam or ham.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv('./datasets/spam.csv', encoding='latin-1')
df = df[['Category', 'Message']]
df['Category'] = df['Category'].map({'ham': 0, 'spam': 1})
df.head()

,Category,Message
0,0,"Go until jurong point, crazy.. Available only ..."
1,0,Ok lar... Joking wif u oni...
2,1,Free entry in 2 a wkly comp to win FA Cup fina...
3,0,U dun say so early hor... U c already then say...
4,0,"Nah I don't think he goes to usf, he lives aro..."


In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    df['Message'], df['Category'], test_size=0.2, random_state=42)
X_train.shape, X_test.shape

((4457,), (1115,))

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
x_train_count = v.fit_transform(X_train.values)
x_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7733))

In [12]:
nb_classifier = MultinomialNB()
nb_classifier.fit(x_train_count, y_train)

MultinomialNB()

In [14]:
x_test_count = v.transform(X_test.values)  # Transform the test data using the same vectorizer
y_pred = nb_classifier.predict(x_test_count)  # Predict using the test data
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')
print('\nClassification Report:\n', classification_report(y_test, y_pred))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, y_pred))

Accuracy: 99.28%

Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       966
           1       1.00      0.95      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115


Confusion Matrix:
 [[966   0]
 [  8 141]]


In [26]:
sample_messages = ['Congratulations! You have won a free ticket!',
                   'Hey, are we still on for lunch today?',
                   'Get 20 percent off your next purchase! discount code: 12345']
sample_tfidf = v.transform(sample_messages)
nb_classifier.predict(sample_tfidf)

array([1, 0, 1])

In [27]:
nb_classifier.score(x_test_count, y_test)

0.9928251121076234

In [32]:
from sklearn.pipeline import Pipeline
c = Pipeline([
    ('vect', CountVectorizer()),
    ('model', MultinomialNB()),
])
c.fit(X_train, y_train)

Pipeline(steps=[('vect', CountVectorizer()), ('model', MultinomialNB())])

In [31]:
c.score(X_test, y_test)

0.9928251121076234